### ISSUE TITLE
IE 9 Highlights / hover showing up in funny places

### ISSUE THREAD

**Issue by dngretsch** [jamietre/ImageMapster#238] opened 2015-09-28 14:27 UTC
In IE9 the highlights are showing up very askew. Im using Wordpress plugin, with no customizations.

http://waterton.swc-dev.com/properties

In attached image, Texas is way up near MN & stretched...
![screen shot 2015-09-28 at 9 26 11 am](https://cloud.githubusercontent.com/assets/14874171/10138224/0deecf92-65c3-11e5-84c1-f6ce9377325f.png)

**Comment by techfg** [comment] 2021-01-30 23:35
Hello @dngretsch -

Thank you for reporting this and apologies for the delayed reply.

I can see from your screenshot that Texas is askew but unfortunately the URL you specified is no longer active so I can't see the code or attempt to reproduce in order to determine why.  Also, it's unclear if it works in other browers and the problem is only with IE9.  If the problem is with all browers, then the likely cause is that your area coords are not accurate.  If the problem is only IE9, then its likely an issue with IM.

If you could update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to take a closer look.

**Comment by techfg** [comment] 2021-03-14 17:30
Hello @dngretsch -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:30 UTC
