### ISSUE TITLE
Area coords not recalculated after small resize

### ISSUE THREAD

**Issue by rakyi** [jamietre/ImageMapster#269] opened 2016-12-23 16:37 UTC
Calling `resize` with only a slightly different width or height than original won't recalculate area coords. It's happening due to [this](https://github.com/jamietre/ImageMapster/blob/master/src/scale.js#L17) line, not sure if removing it won't cause other issues.

**Comment by techfg** [comment] 2021-01-26 08:20
Hello @rakyi -

Thank you for reporting this!  Unfortunately, the link you specified in master branch has changed since you posted this several years back.

If you could please provide a full repro via [jsFiddle](https://jsfiddle.net/) and identify the line of code that you believe is causing the issue in the current master branch, I'd be happy to take a closer look.

Thank you!

**Comment by techfg** [comment] 2021-02-28 02:24
Hello @rakyi -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-28 02:24 UTC

**Comment by siemova** [comment] 2024-12-18 23:22
This is still an issue, which I just encountered myself. I expect the original reporter was referencing [these lines](https://github.com/jamietre/ImageMapster/blob/e11142562f767f393ecf23cd0cfee8100626696a/src/scale.js#L22-L24).

**Comment by techfg** [comment] 2024-12-19 00:12
@siemova -

Thanks for pointing out the lines of code that were likely being referenced by @rakyi in the OP.

As mentioned to him and per our [Bug Report](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, if you could open a new issue with a repro and a clear definition of expected & actual behavior, I'd be happy to take a look and see if this could be improved.

Thank you!

**Comment by siemova** [comment] 2024-12-19 17:30
Okay, I have opened https://github.com/jamietre/ImageMapster/issues/424 for this.

**Comment by techfg** [comment] 2024-12-22 04:34
ImageMapster was working by design, restricting the scaling boundary between 0.98 & 1.02 to protect against potential floating point errors.

A new configuration option has been added in v1.8.1 to enable support for controlling if and how ImageMapster restricts area map coords during a resize.

See [scaleMapBounds](https://jamietre.github.io/ImageMapster/reference/configuration-reference/#scalemapbounds).
