### ISSUE TITLE
IE issues.. 

### ISSUE THREAD

**Issue by Wewill** [jamietre/ImageMapster#109] opened 2013-01-03 15:56 UTC
Hi, 

I have an issue that i can't solve, i read many past issues but nothing appear to success.
Here my map : http://arnoldy.wilhem.free.fr/client/test_ie/template_map.html

I use a lazy loading for css and js. 

Thank you very much in advance,
Wewill

**Comment by techfg** [comment] 2021-02-03 09:38
Hello @Wewill -

I've taken a look at both URLs you specified ([lazy](http://arnoldy.wilhem.free.fr/client/test_ie/template_map.html) & [not lazy](http://arnoldy.wilhem.free.fr/client/test_ie/template_map_without_lazy.html)) and they both appear to be working.

As @jamietre mentioned, the issue is/was likely due to something other than IM the way IM was being loaded (lazy loading) seemed to be the difference between working not working.

That said, since they both appear to be working, I'm guessing you were able to resolve.  Can you confirm so we can close this issue?

**Comment by Wewill** [comment] 2021-02-04 10:15
Hello @techfg, 

Thank you for your feedback, well, as you said, it's so old ; I can't figured out the issue. You can close this ticket for sure. 

Best regards, 
Wilhem

**Closed** 2021-02-04 16:56 UTC
Labels: needs author feedback
