### ISSUE TITLE
Example "resize" crashes on my Android

### ISSUE THREAD

**Issue by k-mikhail** [jamietre/ImageMapster#239] opened 2015-10-05 16:05 UTC
Example "resize" crashes after some time (Web browser Safari is destroyed) when i point (many times) to map elements on my Android.
navigator.userAgent: Mozilla/5.0 (Linux; U; Android 4.4.2; ru-ru; SM-T210 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
memory device: overall volume 8Gb, system 2.72 Gb, busy 4.76 Gb, cached data 63.77 Mb, available space 683 Mb.

**Comment by techfg** [comment] 2021-01-26 08:21
Hello @k-mikhail -

Thank you for reporting this issue and apologies for the delayed reply!

If you could provide a full repro via [jsFiddle](https://jsfiddle.net/) with exact steps to reproduce on Android, I'd be happy to take a closer look.

Thank you!

**Comment by techfg** [comment] 2021-02-28 02:24
Hello @k-mikhail -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-28 02:24 UTC
