### ISSUE TITLE
On FULL HD rounding scaling is bad!

### ISSUE THREAD

**Issue by ghost** [jamietre/ImageMapster#211] opened 2014-07-15 20:51 UTC
Line 3956:
 // make sure a float error doesn't muck us up
if (pct > 0.98 && pct < 1.02) { pct = 1; }

When you have FULL HD image and scroll (1920px to 1907px) it was rounded like there was no scroll. And I have waisted few hours to investigate this.

**Comment by belkaaa** [comment] 2018-03-31 14:26
I confirm, there is such a bug!

**Comment by techfg** [comment] 2021-01-31 00:42
Hello @adamm88 -

Thank you for reporting this, apologies for the delayed reply!

While I can see where this might be an issue, without a repro its difficult to validate and identify a potential fix.  Based on the code you mentioned, I can see from reviewing that it is likely to cause issues in certain scenarios.

If you could update this ticket per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines including a full repro and full details of expected vs. actual, we'd be happy to investigate further.

**Comment by techfg** [comment] 2021-03-14 17:34
Hello @ghost -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:34 UTC
Labels: bug

**Comment by techfg** [comment] 2024-12-22 04:34
ImageMapster was working by design, restricting the scaling boundary between 0.98 & 1.02 to protect against potential floating point errors.

A new configuration option has been added in v1.8.1 to enable support for controlling if and how ImageMapster restricts area map coords during a resize.

See [scaleMapBounds](https://jamietre.github.io/ImageMapster/reference/configuration-reference/#scalemapbounds).
