### ISSUE TITLE
Opacity issue in chrome on image hover

### ISSUE THREAD

**Issue by shanky90** [jamietre/ImageMapster#185] opened 2014-02-05 12:43 UTC
I am using this plugin to get map search functionality. I found the issue in chrome browser and for rest, it is working fine.
here is my code:

$('#mapCountry').mapster({
            singleSelect : true,
            render_highlight : { altImage : 'images/img1.gif' },
            mapKey: 'color',
            fill : true, altImage : 'images/img1.gif',
        });

**Comment by techfg** [comment] 2021-02-03 07:12
Hello @shanky90 -

Thank you for reporting this, apologies for the delayed reply!

Unfortunately, other than "opacity issue", you don't indicate any specific information with regards to what the issue is.  If you could update this ticket per our [Bug Report](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to investigate further.

**Comment by techfg** [comment] 2021-03-14 17:37
Hello @shanky90 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:37 UTC
