### ISSUE TITLE
Can't hover / highlight / select in correct area of map

### ISSUE THREAD

**Issue by djmags** [jamietre/ImageMapster#252] opened 2016-03-04 06:25 UTC
I have a map with several 3,4 and 5 sided polygons. The problem is that the mouse needs to be 10-20 px to the right or left of an area to get highlighted or selected. Hovering the mouse above the area doesn't do anything. I tested with some circular areas and they seem to do much better than the polygons. 

I'm pretty sure the map size matches the image size and toggling scaleMap doesn't seem to do much. Some of the polygons are a little funny shaped (my fault) but even the triangles don't work well. Any thoughts?

https://jsfiddle.net/rblue/vqnvsgy3/4/
http://testsite834750.weebly.com/firefly-map.html

**Comment by techfg** [comment] 2021-01-30 23:01
Hello @djmags  -

Thank you for your inquiry, apologies for the delayed reply and trouble you are encountering!

In reviewing your fiddle, everything IM wise seems to be configured correctly.  My only guess is that your area coords are not accurate based on the image itself.  Unfortunately, I'm not sure which "location" in the image is supposed to highlight in relation to the area elements themselves.  You indicate 10-20 px to right/left but I would need to know more specifically where on the image the area "should" be related to.

Based on what I can tell, the problem is likely that your area coords are not accurate as other examples of IM behave as expected especially with this basic of an IM configuration.

I have updated your [fiddle](https://jsfiddle.net/techfg/5y318k0r/2/) to use the latest version of IM (v1.5.1) and added a function to display the tooltip to help with troubleshooting. 

If you could double-check the coords and from there, if you still believe there is an issue with IM, please provide more specifics (e.g. screenshots) so that we can evaluate further.

**Comment by techfg** [comment] 2021-03-14 17:29
Hello @djmags -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:29 UTC
