### ISSUE TITLE
tooltip not working after image map position changed

### ISSUE THREAD

**Issue by kokers** [jamietre/ImageMapster#172] opened 2013-12-10 16:55 UTC
I have two level map. One level is visible on page load, second one is hidden.
I created http://jsfiddle.net/5Kwuf/1/ to show the problem. 

Click on level0,level1 to switch between levels. Tooltip is working ok on hover on both levels. 

I have extra menu list where you can select state (+show tooltip) by clicking on it. It works perfect for visible level. But when I change level and try to select state from outside of map I got:

`Uncaught TypeError: Cannot read property 'template' of undefined`

although state has been proberly selected - only tooltip doesn't show up. Hover with tooltip works fine. 

If I go to second level without 'activating' first level map (I mean, no hover, no selecting state from outside) tooltip works fine for second level but it doesn't work for the first one.

I tried also with `boundList` but it doesn't change a thing. 

Also I wanna to see if there are any selected keys or something with this:

`console.log($('img').mapster('get'));`

but I always got an error:

`Uncaught Can't access data until binding complete.`

**Comment by techfg** [comment] 2021-02-03 08:42
Hello @kokers -

Thank you for your inquiry, apologies for the delayed reply!

I've reviewed your fiddles and believe I have identified why you were encountering the issues you experienced.

1) `Uncaught TypeError: Cannot read property 'template' of undefined` - The reason for this was caused a by a bug in the version of IM that you were using.  In short, if you did not specify an option parameter in the `tooltip` API call, the exception would be encountered.  The workaround is to pass an options parameter even if its empty (e.g. `$(...).mapster('tooltip', 'KS', {})`) or do update to the latest version of IM where this bug is addressed.

2) `Uncaught Can't access data until binding complete.` - The reason for this is due to the way that you are calling the `get` API.  Your selector is `$('img')` which will locate ALL img elements on the page.  Once mapster is initialized, it creates internal elements including `img` elements.  All elements that mapster creates have the `mapster_el` class attached.  The issue here is that by selecting all `img` elements, you are invoking the mapster call on mapsters internal `img` elements which don't themselves have mapster attached.  To correct this, you can change your selector to `$('img[usemap]')` so that only `img` elements that have a `usemap` attribute will be selected.  Better yet, it's always advisable to associate your own classes or ids to ensure you properly locate the correct elements when using selectors.

3) Tooltip issues - There are two issues here:
    1. In your mapster initialization, you only specify an area item for `key = 'all'`, however when invoking the `tooltip` API you are passing the state abbreviation (e.g. `KS`).  Since there is no area configuration for `KS`, IM correctly identifies that there is no tooltip for `KS` and therefore no tooltip is displayed.  To correct this issue, you would need to specify an area for each state abbreviation and including a `toolTip` property.
    2. When you invoke `toolTip`, mapster will only evaluate/process the first item in the selector list.  Since you were using `img` as your selector, mapster will use the whichever image is in the list, apply the tooltip (if there is one) and stop.  This is intentional since mapster will only ever display one tooltip at a time for a given imagemap.  It is possible to display a tooltip for level0 and level1 simultaneously but you would need to invoke `tooltip` API on each individual imagemap.

I've adjusted your [fiddle](http://jsfiddle.net/techfg/41xrkhge/29/) with corrections to these issues using the latest version of IM (v1.5.1 currently).   

On a related note, as you'll see in the [CHANGELOG](), v1.4.0 introduced several fixes and enhancements related to tooltips which simplifies the code required for what you are trying to achieve and avoids the requirement of having to specify an area configuration object with a tooltip for each area.

Please see this [fiddle](http://jsfiddle.net/techfg/arnd9tkp/1/) that achieves the same result of the previous but with much less code/config.

Please let me know if this addresses your issue regarding the exceptions/errors and unexpected behavior.

**Comment by techfg** [comment] 2021-03-14 17:37
Hello @kokers -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:37 UTC
