### ISSUE TITLE
Tooltip and href stoped working

### ISSUE THREAD

**Issue by asimsaleemgit** [jamietre/ImageMapster#293] opened 2018-04-17 12:58 UTC
`<center>
                                    <img id="ctl00_cphMainContent_img" class="img-responsive visible-sm visible-md visible-lg" />
                                </center>
                                <map id="ctl00_cphMainContent_imgMap" class="visible-sm visible-md visible-lg" name="hart-web">
                                    
                                            <area href="Section.aspx?OrigSection=&amp;vsection=A" id="ctl00_cphMainContent_rep_ctl00_areaImgMap" state="E" class="visible-sm visible-md visible-lg" shape="poly" coords="107,70,107,150,182,150,182,70" imagepath="" title="At least 1 tickets available">
                                        
                                            <area href="Section.aspx?OrigSection=&amp;vsection=B" id="ctl00_cphMainContent_rep_ctl01_areaImgMap" state="E" class="visible-sm visible-md visible-lg" shape="poly" coords="106,162,106,244,182,244,182,162" imagepath="https://cdn.universitytickets.com/clients/v30-dev/viewfromseat/b41d67ba-6a7e-40e7-9dcf-10538a1fb331.jpg" title="At least 1 tickets available">
                                        
                                            <area href="Section.aspx?OrigSection=&amp;vsection=C" id="ctl00_cphMainContent_rep_ctl02_areaImgMap" state="E" class="visible-sm visible-md visible-lg" shape="poly" coords="106,255,181,255,181,336,106,336" imagepath="http://img.universitytickets.com/dev/black-grad.gif" title="At least 1 tickets available">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl03_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="https://cdn.universitytickets.com/clients/v30-dev/viewfromseat/add(10).gif" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="264,407,339,407,339,109,264,109" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl04_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="http://img.universitytickets.com/dev/edit-customer.gif" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="195,440,277,440,277,491,295,491,295,513,195,513" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl05_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="http://img.universitytickets.com/dev/add-note.gif" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="311,491,311,512,408,512,408,440,328,440,328,491" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl06_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="510,60,510,469,586,499,586,61" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl07_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="486,491,449,526,153,526,118,491,73,526,73,540,528,540,528,525" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl08_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="420,513,443,513,496,461,496,438,426,438,426,442,420,442" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl09_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="http://img.universitytickets.com/dev/Penguins.jpg" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="420,348,497,348,497,424,420,424" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl10_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="423,254,498,254,498,336,423,336" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl11_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="421,163,497,163,497,243,421,243" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl12_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="422,70,497,70,497,151,422,151" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl13_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="205,108,249,108,249,407,205,407" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                            <area href="#" id="ctl00_cphMainContent_rep_ctl14_areaImgMap" tooltip="Not available to these ticket types: Student." imagepath="" class="visible-sm visible-md visible-lg" onclick="alert('Not available to these ticket types: Student.'); return false;" state="D" coords="354,109,399,109,399,406,354,406" shape="poly" title="Not available to these ticket types: Student.">
                                        
                                </map>

<script type="text/javascript">
$(document).ready(function () {
            

            var imageDesktop = $('#ctl00_cphMainContent_img');

            var data = $.parseJSON($('#map-data').text());
            var data2 = $.parseJSON($('#map-data2').text());

            imageDesktop.mapster({
                mapKey: 'state',
                showToolTip: true,
                clickNavigate: true,
                onConfigured: function () {
                       var csv = data.join(',');
                       var csv2 = data2.join(',');

                    imageDesktop.mapster('set', true, csv, { fillColor: 'ffffff', staticState: true, stroke: true, showToolTip: true, clickNavigate: true });
                    
                }
            });

        });
</script>
    <script type="application/json" id="map-data">
     ["D" ]
</script>
    <script type="application/json" id="map-data2">
     ["E" ]
</script>`

I am applying ImageMapster and tooltip / href stopped working. Please help.

**Comment by techfg** [comment] 2021-01-26 09:10
Hello @asimsaleemgit -

Thank you for your inquiry, apologies for the delayed reply!

Unfortunately, the code you pasted in your OP did not format well and you didn't provide any steps to reproduce the behavior you are encountering.

Please see information about filing [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) and provide a [jsFiddle](https://jsFiddle.net) will steps to reproduce along with actual behavior vs expected behavior and I'll be happy to take a closer look.

**Comment by techfg** [comment] 2021-02-28 02:25
Hello @asimsaleemgit -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-28 02:25 UTC
