### ISSUE TITLE
How to bring some content over the imagemapster ?

### ISSUE THREAD

**Issue by prem444** [jamietre/ImageMapster#279] opened 2017-04-12 06:07 UTC
Hello,

i have just made an attempt to work on imagemapster, i looked into http://www.outsharked.com/imagemapster/default.aspx?docs.html#tooltip for help and also i got marked for some layout, right now i'm able to get the blink for the selected coords i have made, the issue is that i'm not able to put some content over there and how. Because i added a additional <div> between one of the coordinates but i'm not able to get the content over that as soon as i select that area. please can anyone resolve it to overcome from that ?

**Comment by techfg** [comment] 2021-01-30 21:31
Hello @prem444 -

Thank you for your question, apologies for the delayed reply!

Unfortunately, I'm not exactly sure what the issue is that you are having and without having a repro of the issue and/or seeing your code, it's difficult to say what the problem is.

If you could update your issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) guidelines, I'd be happy to take a closer look.

**Comment by techfg** [comment] 2021-03-14 17:24
Hello @prem444 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:24 UTC
