### ISSUE TITLE
Image mapster, help with mouseover event

### ISSUE THREAD

**Issue by infatum1** [jamietre/ImageMapster#288] opened 2017-11-19 09:43 UTC
Trying to highlight chemical elements in a periodic table with image mapster - http://chemistrytable.scienceontheweb.net/index_eng.php
The following is code is used:

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.js"></script>
<script type="text/javascript" src="js/jquery.imagemapster.js"><script>
		 <script>$('Map').mapster();
	  $('#Map').mapster({
	      fillColor: 'ff0000',
        fillOpacity: 0.3
    });
</script>

I guess I'm missing something. 

p.s. I'm really hoping somebody developing HTML6 or CSS4 will think about applying styles and js to <area> tag.

**Comment by techfg** [comment] 2021-01-30 20:51
Hello @infatum1 -

Apologies for the long delay in reply!

Unfortunately the URL you indicated is no longer available so I can't take a look.  Your description of the problem is fairly vague so its difficult to know exactly what the problem was.  My only guess is that the map wasn't highlight but I'm not sure if there was an error, if nothing was working, if some pieces were working but highlight wasn't. etc.

One thing I noticed in your script is that you are applying ImageMapster two to different HTML elements, possibly you have two different images?

Please let us know if this is still an issue for you and if so, would be happy to take a look but please provide more details per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.  Thank you!

**Comment by techfg** [comment] 2021-03-14 17:24
Hello @infatum1 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:24 UTC
