### ISSUE TITLE
This plugin cannot be used？

### ISSUE THREAD

**Issue by liangnianbing** [jamietre/ImageMapster#298] opened 2018-09-17 07:51 UTC
**### I use it according to your example, but my demo didn't work.**

```<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<title>图片热点</title>
	<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
	<script src="./jquery.imagemapster.min.js"></script>
	<script>
		$(function(){
			$('img').mapster( { 
    			fillColor: 'ff0000', 
    			stroke: true, 
    			singleSelect: true
			});
		});
	</script>
</head>
<body>
	<div id="haha">
		<img src="https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2069625180,2162766275&fm=27&gp=0.jpg" >
	</div>
	
</body>
</html>```

**Comment by jcastillob** [comment] 2018-09-27 19:44
it will not work with jquery 3, you need to use an older version(1.3.2) [Stackoverflow question](https://stackoverflow.com/questions/52109183/imagemapster-for-jquery-3-1-1/52116920#52116920)

Or you can update to use $.noConflict()

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    
    <script type="text/javascript">
        var jQuery_3_3_1 = $.noConflict(true);
    </script>

    
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.3.2.js"></script>

    
    <script type="text/javascript">
        var jQuery_1_3_2 = $.noConflict(true);
    </script>

**Comment by techfg** [comment] 2021-01-11 15:59
Hello @liangnianbing -

You do not mention what is not working nor what version of imagemapster you are using, but based on your example, I do not believe this is a jQuery version problem but rather you do not have a map element nor area elements and your img does not specify the usemap attribute. On a related note, as of imagemapster v1.2.13, jQuery 3.3.1 should work as expected.

Your html should look similar to the following:

```
<div id="haha">
   <img usemap="#mymap" src="https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2069625180,2162766275&fm=27&gp=0.jpg" >
   <map name="mymap" .... />
  <area .... />
   <area .... />
   etc.
</div>
```

Please have a closer look at the code behind the example and/or see this [jsFillde](http://jsfiddle.net/nYkAG/).

If you continue to have issues, please provide a [jsFiddle](https://jsfiddle.net/) that reproduces the issue.

**Comment by techfg** [comment] 2021-02-13 00:27
Hello @liangnianbing -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-13 00:27 UTC
