### ISSUE TITLE
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by antobine** [jamietre/ImageMapster#225] opened 2015-02-06 01:07 UTC
Hi everybody!! First of all, I',m very greateful for this wonderful plugin. I wanted to ask for some help becuase I'm having trouble getting multiple altImages to work. When I hover over some state I get this error in the console:
**Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': No function was found that matched the signature provided.** graphics.js:215

I even get this error with the example file provided called altimages.html. [Link here](http://prismadesign.com.ar/imapster/examples/altimages.html) This makes me think there's something wrong with my setup, but I can't figure out what it is. I really hope someone could give me a hand. Thanks in advanced!!

**Comment by balazsbohonyi** [comment] 2015-10-02 07:13
Stumbled upon this same issue. The example is incorrect.
For render_select and render_highlight, to specify the alternative image, use altImageId, not altImage as it is in the example:

```javascript
render_highlight: {
altImageId: 'img01'
},
render_select: {

stroke: false,
fillOpacity: 0,
altImageOpacity: 0.5,
altImageId: 'img01'

}
```

**Comment by techfg** [comment] 2021-01-31 00:08
Hello @antobine -

Thank you for reporting this and apologies for the delay reply.

Unfortunately, the link you indicated is no longer active so I can't try to reproduce the behavior. That said, as @balazsbohonyi mentions, the property `altImage` is inteded to contain a URL path while `altImageId` is intended to be the ID of a pre-configured altImage.  It appears that possibly the code was using this incorrectly and hence the issue you were encountering.

If that's not the case and if this is still an issue for you, please update this ticket per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'll be happy to investigate further.

**Comment by techfg** [comment] 2021-03-14 17:35
Hello @antobine -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:35 UTC
