### ISSUE TITLE
Tooltip content on inner area

### ISSUE THREAD

**Issue by thenetbreeze** [jamietre/ImageMapster#102] opened 2012-12-01 08:23 UTC
I am contacting you directly because of my deadline for a project. In this project I use your grate ImageMapster plugin. My problem - beside my poor English - is that I have one inner area inside another area (like in your inner circles example in docs section). Both areas are rendered correctly as selected areas. But when I mouseover the inner area, the tooltip has the same content as the outer area. What should I code in order to show in the tooltip the content of toolTip value for inner area (which is already setted).

Thank you in advance for any suggestion,

**Comment by techfg** [comment] 2021-02-21 07:47
Hello @thenetbreeze -

Thank you for your inquiry, apologies for the delayed reply!

I've taken a look at this but am unable to reproduce.  If you could update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to investigate this further.

**Comment by techfg** [comment] 2021-03-26 05:35
Hello @thenetbreeze -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-26 05:35 UTC
