### ISSUE TITLE
IE8 compatibility: stroke-only areas not displayed?

### ISSUE THREAD

**Issue by silver-quettier** [jamietre/ImageMapster#218] opened 2014-11-20 15:02 UTC
_From what I read, posts about IE compatibility are legion, yet I could not find a solution to my problem. I checked the usual stuff: trailing commas, etc._

My use case is very simple. 
See this fiddle: http://jsfiddle.net/tgpkjaqu/
Embedded version for IE: http://jsfiddle.net/tgpkjaqu/embedded/result/

**I cannot get any area to display on IE8. Am I doing something wrong?**

Here is the code again:

**HTML**

```
<img id="realmap" usemap="#shapes" width="563" height="410" src="http://nzetc.victoria.ac.nz/etexts/WH2Paci/Wh2Pac32a.jpg" alt="Current map"/>
                    <map name="shapes" id="shapes">
                        <area class="areaGreen" alt="" title="" href="#" shape="poly" coords="111,39,119,39,119,81,111,81" />
                        <area class="areaBlinkingRed" alt="" title="" href="#" shape="poly" coords="505,277,505,318,539,318,539,277" />
                        <area class="areaOrange" alt="" title="" href="#" shape="poly" coords="376,11,557,11,557,148,484,148,484,34,376,34" />
                    </map>
```

**JS**

```
$("#realmap").mapster({
    areas: [
        {
            key: "areaBlinkingRed",
            strokeColor: "FF0000"
        },
        {
            key: "areaBlinkingOrange",
            strokeColor: "FFA500"      
        },
        {
            staticState: true,
            key: "areaGreen",
            strokeColor: "008000"      
        },
        {
            staticState: true,
            key: "areaRed",
            strokeColor: "FF0000"
        },
        {
            staticState: true,
            key: "areaOrange",
            strokeColor: "FFA500"     
        }
    ],
    strokeWidth: 3,
    stroke: true,
    highlight: false,
    fill: false,
    mapKey: "class"
});
```

**Comment by techfg** [comment] 2021-01-31 00:34
Hello @silver-quettier -

Thank you for your inquiry, apologies for the delayed reply!

Unfortunately, I'm not sure what you mean by "cannot get any area to display" - do you mean the image itself doesn't display or that it does display but areas do not highlight/select?

I took a look at your fiddle and noticed that you were using an inline script tag vs. a resource which was causing issues since IM wasn't loading properly.  Possibly this is the root cause of your issue but I'm guessing that's not the case.

If this is still an issue for you, please provide a current working fiddle with specific information on what the actual behavior vs. expected behavior is per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'll be happy to investigate.

**Comment by techfg** [comment] 2021-03-14 17:33
Hello @silver-quettier -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:33 UTC
