### ISSUE TITLE
Imagemapster with Ionic3 (Angular5)

### ISSUE THREAD

**Issue by vishwa12345** [jamietre/ImageMapster#303] opened 2019-03-27 09:51 UTC
Iam trying to use imagemapster plugin with Ioinc3 and Angular5 combination, I tried using JQuery method, it is not working. May i know to implement this?

Thanks in Advance

**Comment by techfg** [comment] 2021-01-11 15:38
Hello @vishwa12345 -

Unfortunately, you haven't provided any information regarding how you are loading imagemapster and what is not working. As of v1.3.0, imagemapster provides full UMD support and can be installed via NPM (assuming you are trying to use it this way possibly).  Please try installing/using the [latest version](https://github.com/jamietre/ImageMapster/releases/latest) and if you continue to have issues, please provides steps to reproduce.

**Comment by techfg** [comment] 2021-02-13 00:27
Hello @vishwa12345  -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-13 00:27 UTC
