### ISSUE TITLE
"mapKey" breaks ImageMapster in IE

### ISSUE THREAD

**Issue by ghost** [jamietre/ImageMapster#145] opened 2013-06-13 21:57 UTC
My imagemap is working fine in Firefox and Chrome, but not at all in IE 8. No fill on hover. No tooltips.

This is it:
http://cashmagic.runcus.com/locations/
The blue areas of the map are active.

If I remove the "mapKey" portion from my javascript, the hotspots now change color when they're hovered over. Why would the mapKey line break imagemapster in IE 8?

**Comment by intrepidws** [comment] 2015-01-06 21:43
Did you ever figure out a solution for this?

**Comment by techfg** [comment] 2021-02-03 04:29
Hello @ghost -

Thank you for reporting this, apologies for the delayed reply.

Unfortunately, the URL you provided is no longer active so I'm unable to reproduce without knowing more specifically how the code was configured, etc.  From your OP, it sounds like the mere presence of `mapKey` configuration option was causing the issue which would indeed be very odd and @jamietre indicates not being able to repro at least in IE8 mode of IE10.  Possibly this was an issue with stock IE8 but difficult to say.

If this is still an issue for you, please update this ticket per the [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate further.

**Comment by techfg** [comment] 2021-03-14 17:36
Hello @ghost -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:36 UTC
