### ISSUE TITLE
HiDPi screens

### ISSUE THREAD

**Issue by davebeesleyarchived** [jamietre/ImageMapster#195] opened 2014-04-11 14:38 UTC
Hi.
I'm having an issue with your wonderful tool on hi DPi screens, like the iPhone 5C.
The main image is fine, but the overlay is blurry and pixellated.
I may be wrong, but I think it is related to the canvas elements mapster creates, and how they render.

http://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by leinvaim** [comment] 2016-08-25 05:39
having same issue, did you find any solution for this?

**Comment by techfg** [comment] 2021-02-03 03:53
Hello @davebeesleyarchived -

Thank you for bringing this to our attention, apologies for the delayed reply!

Unfortunately, without a repro of the issue its difficult to say for certain what might be the cause.  I'm not seeing this issue manifest on high DPI screens currently but that doesn't mean that there isn't an issue still present.

If you could update this issue per our [Bug Report](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and include a repro, screenshots, etc. we'd be happy to investigate further.

Thank you!

**Comment by techfg** [comment] 2021-03-14 17:35
Hello @davebeesleyarchived -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:35 UTC
