### ISSUE TITLE
TypeError: mapster() is not a function

### ISSUE THREAD

**Issue by DriesDebouver** [jamietre/ImageMapster#302] opened 2019-03-10 16:19 UTC
Dear,

I get the error: "TypeError: mapster() is not a function" when trying to call the .mapster() function inside a .click( function( ) { ... } );
I want that a specific area get's selected when clicking on the "Add" button in a table row with the help of a CategoryId.
When trying this outside the .click() function from the button with a hardcoded CategoryId it works.

Here is the JavaSript code:
```
$("#add").click(function() {
            alert("Clicked");
            CategoryId = $("#add").val();
            alert("ID = " + CategorieId)
            $('area.' + CategoryId).mapster('select');
});
```

This is the html:
`<td><button id="add" value="@item.CategoryId">Add</button></td>`

When trying this outside the click function it works:
`$('area.17').mapster('select');`

What is wrong with the code and can the .mapster() function be used inside a .click() function?

Thanks.

**Comment by techfg** [comment] 2021-01-11 18:45
Hello @DriesDebouver -

Assuming you are running the code you have provided from the same page, there should be no reason why this is occurring.  Without a full repro, there's not a clear answer.

What you are trying to do should work as demonstrated in this [jsFiddle](http://jsfiddle.net/techfg/Lsnp6jrw/2/).

If this doesn't help, please provide a full jsFiddle that reproduces the problem and we'll be happy to take a look.

**Comment by techfg** [comment] 2021-02-13 00:25
Hello @DriesDebouver  -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-13 00:25 UTC
