### ISSUE TITLE
bug wordpress

### ISSUE THREAD

**Issue by worldwildweb** [jamietre/ImageMapster#309] opened 2020-09-22 10:23 UTC
Hello there, 
i was wondering if you were aware that ImageMapster 1.2.6 is not compatible with wordpress 5.5.1
I have deactivated the plugin at the moment since it crashed some other functionalities.

![image](https://user-images.githubusercontent.com/1954918/93870410-7afb3480-fccd-11ea-89a2-b966e63cbe7f.png)

https://www.master-bmc-universite-paris.fr/biomolecules-biologie-et-pathologies-moleculaires-bbpm/#

**Comment by techfg** [comment] 2021-01-11 15:35
Hello @worldwildweb - 

Without any details regarding how you are loading imagemapster, what browser you are using, etc. its difficult to say what the issue is.  With that said, version 1.2.6 is extremely old so please update to the latest version (currently [v1.3.1](https://github.com/jamietre/ImageMapster/releases/tag/v1.3.1) and if you still have issues, please provide steps to reproduce.

**Comment by techfg** [comment] 2021-02-13 00:22
Hello @worldwildweb -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-02-13 00:22 UTC
