### ISSUE TITLE
Image mapster map can't be bigger than 720x494px?

### ISSUE THREAD

**Issue by Adyyda** [jamietre/ImageMapster#236] opened 2015-09-18 12:48 UTC
Hello. I have found that if i use a responsive map bigger than 720px, it will render fine in chrome and firefox but on ie8 the black hover is misplaced.
![map](https://cloud.githubusercontent.com/assets/5921012/9959414/77d286aa-5e1c-11e5-996e-b6301f6b316f.jpg)

As you can see in the image we have some additional inline attributes for width and height that cancel any setting that i apply. 

How can i fix this issue?

**Comment by techfg** [comment] 2021-01-30 23:41
Hello @Adyyda -

Thank you for your inquiry and apologies for the delayed reply!

When mapster is applied to an image, it wraps the `img` with a `div` tag.  By default, it will determine the `img` width & height and apply it to the wrapper div.  If you would like to apply additional css to the wrapper, you can utilize the `wrapClass` and `wrapCss` options of imagemapster.  Please see the [docs] for more information on these.

Based on your description, its not 100% clear to me what the issue is so I would need more information to help you identify.  When you say "misplaced", can you describe more specifically what you mean?  

If this is still an issue for you, if you could follow our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and update this ticket and provide a full repro, we'd be happy to investigate further.

**Comment by techfg** [comment] 2021-03-14 17:30
Hello @Adyyda -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:30 UTC
