### ISSUE TITLE
Imagemapster crashes Chrome while Initializing

### ISSUE THREAD

**Issue by acolwell625** [jamietre/ImageMapster#245] opened 2015-10-30 14:49 UTC
After the last Chrome update, every time my map goes to initialize via JSON data, chrome crashes, has anyone else experienced this issue? If so, what did you do to correct it? Thanks in advance.

**Comment by techfg** [comment] 2021-01-30 23:15
Hello @acolwell625  -

Thank you for reporting this, apologies for the delayed reply.

Unfortunately, without knowing what version of Chrome you were having the issue with nor what "crash" means specifically, its difficult to say what the problem is/was.

Please let us know if this is still an issue for you and if so, please update this ticket per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate further.

**Comment by techfg** [comment] 2021-03-14 17:29
Hello @acolwell625 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

**Closed by techfg** 2021-03-14 17:29 UTC
